export const FETCH_USER_REPOS_REQUEST = "FETCH_USER_REPOS_REQUEST";
export const FETCH_USER_REPOS_SUCCESS = "FETCH_USER_REPOS_SUCCESS";
export const FETCH_USER_REPOS_FAILURE = "FETCH_USER_REPOS_FAILURE";
